lib/magnetis_accounts_web/router.ex
defmodule MagnetisAccountsWeb.Router do
  use MagnetisAccountsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MagnetisAccountsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", WebConsoleController, :show

    post "/input", InputController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", MagnetisAccountsWeb do
  #   pipe_through :api
  # end
end

lib/magnetis_accounts_web/controllers/web_console_controller.ex
defmodule MagnetisAccountsWeb.WebConsoleController do
  use MagnetisAccountsWeb, :controller

  alias MagnetisAccounts.Account

  def show(conn, _params) do
    accounts = Account.all

    conn
    |> assign(:accounts, accounts)
    |> render("show.html")
  end
end

lib/magnetis_accounts_web/views/web_console_view.ex
defmodule MagnetisAccountsWeb.WebConsoleView do
  use MagnetisAccountsWeb, :view
end

lib/magnetis_accounts_web/templates/web_console/show.html.eex
<div class="pa4-l mw7 center pa4">
  <%= form_for @conn, input_path(@conn, :create), fn _ -> %>
    <fieldset class="cf bn ma0 pa0">
      <div class="cf">
        <label class="clip" for="inputValue">Input Command</label>

        <input class="f6 f5-l input-reset ba fl black-80 bg-white pa3 lh-solid w-100 w-75-m w-80-l br2-ns br--left-ns"
               placeholder="Input Command"
               type="text"
               name="value"
               id="inputValue">

        <input class="f6 f5-l button-reset fl pv3 tc ba b--dark-gray bg-dark-gray hover-bg-black white pointer w-100 w-25-m w-20-l br2-ns br--right-ns"
               type="submit"
               value="Send">
      </div>
    </fieldset>
  <% end %>

  <%= if get_flash(@conn, :info) do %>
    <p class="w-100 bg-dark-green pa3 white br2" role="alert"><%= get_flash(@conn, :info) %></p>
  <% end %>

  <%= if get_flash(@conn, :error) do %>
    <p class="w-100 bg-dark-red pa3 white br2" role="alert"><%= get_flash(@conn, :error) %></p>
  <% end %>

  <h2 class="tc mt6">Account Ids</h2>
  <div class="overflow-auto">
    <%= Enum.map(@accounts, fn account -> %>
        <span class="b"><%= account.id %></span>, 
    <% end) %>
  </div>
</div>